# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tindew-swipe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Shuffle-iOS'
  # Pods for tindew-swipe

  target 'tindew-swipeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tindew-swipeUITests' do
    # Pods for testing
  end

end
